### PR TITLE
add hstshijack proxy module

### PR DESCRIPTION
**Pull request by yungtravla**
I posted a video on Twitter showing this in action :)

<a href="https://twitter.com/yungtravla/status/1004909625789956096" target="_blank">https://twitter.com/yungtravla/status/1004909625789956096</a>

### CODE REVIEW

**Comment by alexmozzhakov** [comment]
```[sys.log] [err] Unknown or invalid syntax "hstshijack.show", type help for the help menu.```

**Comment by yungtravla** [comment]
@alexmozzhakov  does it output the config as well as the error or just the error?

**Comment by yungtravla** [comment]
oh you said after showing info, yeah i know it throws unnecessary error

**Comment by alexmozzhakov** [comment]
@yungtravla np, fixed it. Seems like `onCommand(cmd)` needs to return boolean:
https://github.com/bettercap/bettercap/blob/a3ef4e66f0758d1958aed71f99c6bd574fbeebe5/modules/http_proxy_script.go#L177

**Comment by yungtravla** [comment]
@alexmozzhakov cool, thanks :)

**Pull request merged**
